# Meson cross-compilation file for Android aarch64 (API 31)
# NDK r27d with aarch64-linux-android31-clang
#
# Usage:
#   meson setup builddir --cross-file cross/android-aarch64-api31.ini [options]

[constants]
ndk_path = '/home/vince/android/lxc/_ndk/android-ndk-r27c'
toolchain = ndk_path / 'toolchains/llvm/prebuilt/linux-x86_64'

[binaries]
c = toolchain / 'bin/aarch64-linux-android31-clang'
cpp = toolchain / 'bin/aarch64-linux-android31-clang++'
ar = toolchain / 'bin/llvm-ar'
strip = toolchain / 'bin/llvm-strip'
ranlib = toolchain / 'bin/llvm-ranlib'
ld = toolchain / 'bin/ld.lld'
objcopy = toolchain / 'bin/llvm-objcopy'
objdump = toolchain / 'bin/llvm-objdump'
readelf = toolchain / 'bin/llvm-readelf'
nm = toolchain / 'bin/llvm-nm'
pkgconfig = 'false'

[built-in options]
c_args = ['-O2', '-fdata-sections', '-ffunction-sections', '-DANDROID', '-Wno-unused-command-line-argument']
c_link_args = ['-Wl,--gc-sections', '-Wl,--as-needed', '-Wl,-z,relro', '-Wl,-z,now']

[properties]
sys_root = toolchain / 'sysroot'
needs_exe_wrapper = true

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'
